# Generated by Django 6.0 on 2025-12-24 18:23

import ORMapp.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[ORMapp.models.validate_name_starts_with_a])),
                ('website', models.URLField()),
                ('date_opened', models.DateField()),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('restaurent_type', models.CharField(choices=[('INIndian', 'Indian'), ('CHChines', 'Chines'), ('ITItalian', 'Italian'), ('GRGreek', 'Greek'), ('MXMexican', 'Mexican'), ('FDFastfood', 'Fastfood'), ('OTOther', 'Other')], max_length=10)),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': ['date_opened'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ORMapp.restaurent')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('restaurent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='ORMapp.restaurent')),
            ],
        ),
        migrations.CreateModel(
            name='StaffRestaurent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORMapp.staff')),
                ('restaurent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORMapp.restaurent')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='restaurents',
            field=models.ManyToManyField(through='ORMapp.StaffRestaurent', to='ORMapp.restaurent'),
        ),
    ]
