# Generated by Django 6.0 on 2025-12-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='expenditure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
