# Generated by Django 6.0 on 2025-12-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0002_sales_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='capacity',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
