# Generated by Django 6.0 on 2025-12-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0003_restaurent_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
